query {
    Crate {
        item {
            ... on Fn {
                body {
                    value {
                        statements {
                            ... on LocalStatement {
                                init {
                                    type {
                                        as_string @output
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
